name: approval_without_env

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    #if: github.event_name == 'pull_request'
    environment: 
      name: Development
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  ApproveProduction:
    name: Approval for Production Deployment
    runs-on: ubuntu-latest
    needs: [DeployStaging]
    steps:
      - name: Request approval
        run: echo "Waiting for approval to deploy to production."
      - name: Approval
        if: ${{ github.event.inputs.approved == 'true' }}
        run: echo "Approved for production deployment."

  DeployProd:
    name: Deploy to Production 
    needs: [ApproveProduction]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo I am deploying!
