name: test and prod

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: echo "Running tests..."

      - name: Deploy to Test
        run: echo "Deploying to Test Environment....."

  ApproveProduction:
    name: Approval for Production Deployment
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Request approval
        run: echo "Requesting approval for production deployment..."
      - name: Approval
        if: ${{ github.event.inputs.approved == 'true' }}
        run: echo "Approved for production deployment."

  DeployProd:
    name: Deploy to Production
    needs: [ApproveProduction]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment..."
